### PR TITLE
Remove 3.7 remnants in docs/metadata

### PR DESCRIPTION
**Pull request by JelleZijlstra**

### CODE REVIEW

**Review by AlexWaygood — APPROVED** [review]

**Review by mauvilsa — COMMENTED** [review]
@JelleZijlstra will 2.5.0 be yanked and 2.5.1 released? I have some unit tests that run on python 3.7, and now they fail because typeshed-client v2.5.0 was incorrectly installed. Would be nice if 2.5.0 gets yanked so that only the latest supported version is installed in 3.7.

**Comment by JelleZijlstra** [comment]
Sure. Didn't realize people would still actually use 3.7 :)

**Comment by JelleZijlstra** [comment]
2.5.1 is released and 2.5.0 is yanked

**Comment by mauvilsa** [comment]
Great, thank you! I will drop support for 3.7, but these things take time and not sure when I will get to it.

**Pull request merged**
